import ProjectDescription

let workspace = Workspace(
    name: "MusicPlayer",
    projects: [
        "App",
        "Data",
        "Network",
    ],
    generationOptions: .options(
        autogeneratedWorkspaceSchemes: .disabled
    )
)
